# Generated by Django 5.0.2 on 2024-02-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanishk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promt', models.CharField(max_length=700)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
