# Generated by Django 5.0.2 on 2024-03-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_kanishk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kanishk',
            new_name='Manishk',
        ),
    ]
