# Generated by Django 5.0.2 on 2024-03-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_kanishk_manishk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manishk',
        ),
    ]
