# Generated by Django 5.0.2 on 2024-03-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_plan_rename_projects_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
