# Generated by Django 5.0.2 on 2024-03-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
