# Generated by Django 5.0.2 on 2024-06-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
